export const SUBCATEGORY_REQUEST = 'SUBCATEGORY_REQUEST'
export const SUBCATEGORY_SUCCESS = 'SUBCATEGORY_SUCCESS'
export const SUBCATEGORY_FAILURE =  'SUBCATEGORY_FAILURE'

export const FLIGHT_REQUEST = 'FLIGHT_REQUEST'
export const FLIGHT_SUCCESS = 'FLIGHT_SUCCESS'
export const FLIGHT_FAILURE = 'FLIGHT_FAILURE'

export const MAINCATEGORY_REQUEST = 'MAINCATEGORY_REQUEST'
export const MAINCATEGORY_SECCESS = 'MAINCATEGORY_SECCESS'
export const MAINCATEGORY_FAILURE = 'MAINCATEGORY_FAILURE'